require('dotenv').config();
const express=require('express');
const cors=require('cors');
const crypto=require('crypto');
const fs=require('fs');
const path=require('path');
const nodemailer=require('nodemailer');
const Razorpay=require('razorpay');
const app=express();
const PORT=Number(process.env.PORT||3000),ROOT=path.join(__dirname,'..'),DATA=path.join(ROOT,'data');
const FILES={products:path.join(DATA,'products.json'),orders:path.join(DATA,'orders.json'),custom:path.join(DATA,'customization-requests.json'),events:path.join(DATA,'webhook-events.json')};
for(const f of Object.values(FILES))if(!fs.existsSync(f))fs.writeFileSync(f,'[]');
const read=f=>JSON.parse(fs.readFileSync(f,'utf8')),write=(f,d)=>fs.writeFileSync(f,JSON.stringify(d,null,2)),now=()=>new Date().toISOString();
const adminSessions=new Map();
const razorReady=!!(process.env.RAZORPAY_KEY_ID&&process.env.RAZORPAY_KEY_SECRET);const razorpay=razorReady?new Razorpay({key_id:process.env.RAZORPAY_KEY_ID,key_secret:process.env.RAZORPAY_KEY_SECRET}):null;
const mailReady=!!(process.env.SMTP_HOST&&process.env.SMTP_USER&&process.env.SMTP_PASS);const mailer=mailReady?nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE).toLowerCase()==='true',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}}):null;
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n)||0);
const clean=s=>String(s??'').replace(/[<>]/g,'');
const findProduct=id=>read(FILES.products).find(p=>p.id===id),findOrder=id=>read(FILES.orders).find(o=>o.id===id||o.razorpayOrderId===id);
function patchOrder(id,patch){const a=read(FILES.orders),i=a.findIndex(o=>o.id===id||o.razorpayOrderId===id);if(i<0)return null;a[i]={...a[i],...patch,updatedAt:now()};write(FILES.orders,a);return a[i]}
function adminAuth(req,res,next){const t=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!t||!adminSessions.has(t))return res.status(401).json({error:'Admin session expired.'});next()}
function same(a,b){if(!a||!b)return false;const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function hmac(secret,data){return crypto.createHmac('sha256',secret).update(data).digest('hex')}
async function email(to,subject,html){if(!mailer||!to)return false;await mailer.sendMail({from:process.env.SMTP_FROM||process.env.SMTP_USER,to,subject,html});return true}
async function orderEmail(o){if(!o||o.confirmationEmailSentAt||!o.email||!mailer)return;const rows=o.items.map(i=>`<tr><td style="padding:8px 0">${clean(i.name)} × ${i.quantity}</td><td style="text-align:right">${money(i.price*i.quantity)}</td></tr>`).join('');const html=`<div style="background:#f8f2ea;padding:40px;font-family:Arial;color:#191715"><div style="max-width:680px;margin:auto;background:white;padding:40px"><div style="font:30px Georgia,serif;letter-spacing:.08em">LEONORA</div><div style="letter-spacing:.2em;font-size:11px">FURNITURE STUDIO</div><hr><h1 style="font:40px Georgia,serif;font-weight:400">Order confirmed ✓</h1><p>Thank you, ${clean(o.shipping?.name)}. Your payment has been successfully verified.</p><p><strong>Order ${clean(o.id)}</strong></p><table style="width:100%">${rows}</table><hr><p><strong>Total paid: ${money(o.total)}</strong></p><p style="color:#71695f">UPI and card payments are processed securely by Razorpay.</p></div></div>`;await email(o.email,'Leonora order confirmed · '+o.id,html);patchOrder(o.id,{confirmationEmailSentAt:now()})}
async function finalizeOrder(orderRef,paymentId){let o=findOrder(orderRef);if(!o)return null;o=patchOrder(o.id,{paymentStatus:'paid',status:'confirmed',razorpayPaymentId:paymentId||o.razorpayPaymentId,paidAt:o.paidAt||now()});if(!o.inventoryDeducted){const products=read(FILES.products);for(const item of o.items){const p=products.find(x=>x.id===item.productId);if(p)p.stock=Math.max(0,Number(p.stock||0)-Number(item.quantity||0));}write(FILES.products,products);o=patchOrder(o.id,{inventoryDeducted:true})}await orderEmail(o).catch(()=>{});return findOrder(o.id)}
app.use(cors());app.use(express.json({limit:'1mb',verify:(req,res,buf)=>{req.rawBody=Buffer.from(buf)}}));app.use(express.urlencoded({extended:true}));
app.post('/api/webhooks/razorpay',async(req,res)=>{try{const sig=req.headers['x-razorpay-signature'];if(!process.env.RAZORPAY_WEBHOOK_SECRET||!same(hmac(process.env.RAZORPAY_WEBHOOK_SECRET,req.rawBody||Buffer.from('')),sig))return res.status(400).json({error:'Invalid webhook signature'});const eventId=req.headers['x-razorpay-event-id']||hmac(process.env.RAZORPAY_WEBHOOK_SECRET,req.rawBody||Buffer.from(''));const seen=read(FILES.events);if(seen.includes(eventId))return res.json({ok:true});seen.push(eventId);write(FILES.events,seen);const p=req.body?.payload||{};const orderId=p.order?.entity?.id||p.payment?.entity?.order_id;const paymentId=p.payment?.entity?.id;if(['order.paid','payment.captured'].includes(req.body?.event)&&orderId)await finalizeOrder(orderId,paymentId);if(req.body?.event==='payment.failed'&&orderId)patchOrder(orderId,{paymentStatus:'failed'});res.json({ok:true})}catch(e){console.error(e);res.status(500).json({error:'Webhook processing failed'})}});
app.get('/api/config',(req,res)=>res.json({razorpayKeyId:process.env.RAZORPAY_KEY_ID||null,currency:'INR',ready:razorReady}));
app.get('/api/products',(req,res)=>res.json(read(FILES.products)));
app.get('/api/orders/:id',(req,res)=>{const o=findOrder(req.params.id);if(!o)return res.status(404).json({error:'Order not found'});res.json(o)});
app.post('/api/orders/create',async(req,res)=>{try{const {email,phone,shipping,items}=req.body||{};if(!email||!phone||!shipping?.name||!shipping?.address||!shipping?.pincode||!shipping?.city||!shipping?.state||!Array.isArray(items)||!items.length)return res.status(400).json({error:'Complete all checkout details.'});const products=read(FILES.products),normalized=[];for(const item of items){const p=products.find(x=>x.id===item.productId||x.id===item.id);if(!p)return res.status(400).json({error:'A selected product is unavailable.'});const quantity=Math.max(1,Number(item.quantity||1));if(Number(p.stock||0)<quantity)return res.status(400).json({error:`Only ${p.stock} units of ${p.name} remain.`});normalized.push({productId:p.id,name:p.name,price:Number(p.price),quantity,image:p.image,color:item.color||item.selectedColor||p.colors?.[0]||'',fabric:item.fabric||item.selectedFabric||p.fabrics?.[0]||''})}const subtotal=normalized.reduce((s,i)=>s+i.price*i.quantity,0),delivery=subtotal>=100000?0:2500,total=subtotal+delivery,id='LEO-'+Date.now().toString().slice(-8);let o={id,email,phone,shipping,items:normalized,subtotal,delivery,total,currency:'INR',status:'payment_pending',paymentStatus:'pending',createdAt:now(),updatedAt:now()};const rows=read(FILES.orders);rows.push(o);write(FILES.orders,rows);if(!razorReady)return res.json({orderRef:id,mode:'setup',razorpay:{key:'',amount:total*100,currency:'INR',orderId:null}});const rp=await razorpay.orders.create({amount:Math.round(total*100),currency:'INR',receipt:id,payment_capture:1,notes:{orderRef:id}});o=patchOrder(id,{razorpayOrderId:rp.id});res.json({orderRef:id,razorpay:{key:process.env.RAZORPAY_KEY_ID,amount:rp.amount,currency:rp.currency,orderId:rp.id}})}catch(e){console.error(e);res.status(500).json({error:e.message||'Unable to create order'})}});
app.post('/api/orders/verify',async(req,res)=>{try{const b=req.body||{},o=findOrder(b.orderRef||b.orderId);if(!o)return res.status(404).json({error:'Order not found'});const orderId=b.razorpay_order_id||b.razorpayOrderId||o.razorpayOrderId,paymentId=b.razorpay_payment_id||b.razorpayPaymentId,signature=b.razorpay_signature||b.razorpaySignature;if(!process.env.RAZORPAY_KEY_SECRET||!same(hmac(process.env.RAZORPAY_KEY_SECRET,`${orderId}|${paymentId}`),signature))return res.status(400).json({error:'Payment verification failed'});const final=await finalizeOrder(o.id,paymentId);res.json({ok:true,orderRef:final.id})}catch(e){console.error(e);res.status(500).json({error:e.message||'Verification failed'})}});
app.post('/api/customization-requests',async(req,res)=>{try{const {productId,email,phone,color,fabric,dimensions,notes}=req.body||{},p=findProduct(productId);if(!p||!p.customizable)return res.status(400).json({error:'This piece does not support customisation.'});if(!email||!phone||!dimensions?.width||!dimensions?.depth||!dimensions?.height)return res.status(400).json({error:'Add contact details and all three dimensions.'});const r={id:'CUS-'+Date.now().toString().slice(-8),productId,productName:p.name,email,phone,color:color||p.colors?.[0]||'',fabric:fabric||p.fabrics?.[0]||'',dimensions:{width:Number(dimensions.width),depth:Number(dimensions.depth),height:Number(dimensions.height)},notes:String(notes||''),status:'submitted',createdAt:now(),updatedAt:now()};const rows=read(FILES.custom);rows.push(r);write(FILES.custom,rows);if(mailer){await email(r.email,'Leonora customisation request received · '+r.id,`<div style="font-family:Arial;padding:30px"><h1 style="font-family:Georgia;font-weight:400">Customisation request submitted successfully.</h1><p>Reference ${clean(r.id)}</p><p>We will contact you regarding the quotation.</p></div>`).catch(()=>{});if(process.env.STUDIO_EMAIL)await email(process.env.STUDIO_EMAIL,'New Leonora customisation request · '+r.id,`<p>${clean(r.productName)}</p><p>${clean(r.email)} · ${clean(r.phone)}</p><p>${clean(r.color)} · ${clean(r.fabric)}</p><p>W ${r.dimensions.width} · D ${r.dimensions.depth} · H ${r.dimensions.height} cm</p>`).catch(()=>{})}res.json({ok:true,id:r.id,requestId:r.id})}catch(e){res.status(500).json({error:e.message||'Unable to submit request'})}});
app.post('/api/admin/login',(req,res)=>{const e=String(req.body?.email||''),p=String(req.body?.password||'');if(e!==String(process.env.ADMIN_EMAIL||'admin@leonora.in')||p!==String(process.env.ADMIN_PASSWORD||'LeonoraAdmin#2026'))return res.status(401).json({error:'Invalid admin credentials.'});const token=crypto.randomBytes(24).toString('hex');adminSessions.set(token,{email:e,createdAt:now()});res.json({token})});
app.post('/api/admin/logout',adminAuth,(req,res)=>{adminSessions.delete(String(req.headers.authorization||'').replace(/^Bearer\s+/i,''));res.json({ok:true})});
function dashboardData(){const orders=read(FILES.orders),products=read(FILES.products),custom=read(FILES.custom),paid=orders.filter(o=>o.paymentStatus==='paid'),sales=paid.reduce((s,o)=>s+Number(o.total||0),0),recent=orders.slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,8),fulfil={Delivered:paid.filter(o=>o.status==='delivered').length,Shipped:paid.filter(o=>['shipped','out_for_delivery'].includes(o.status)).length,Processing:paid.filter(o=>['confirmed','processing','packed'].includes(o.status)).length};return {totalOrders:orders.length,paidOrders:paid.length,totalSales:sales,customRequests:custom.filter(r=>r.status!=='closed').length,inventoryUnits:products.reduce((s,p)=>s+Number(p.stock||0),0),lowStock:products.filter(p=>Number(p.stock||0)<5).length,recent,orderBars:Array.from({length:12},(_,i)=>20+((orders.length*9+i*13)%74)),salesBars:Array.from({length:12},(_,i)=>25+((sales/10000+i*9)%70)),monthly:Array.from({length:12},(_,i)=>15+((sales/100000+i*11)%75)),fulfilment:{Delivered:paid.length?Math.round(fulfil.Delivered/paid.length*100):0,Shipped:paid.length?Math.round(fulfil.Shipped/paid.length*100):0,Processing:paid.length?Math.round(fulfil.Processing/paid.length*100):0}}}
app.get('/api/admin/dashboard',adminAuth,(req,res)=>res.json(dashboardData()));app.get('/api/admin/summary',adminAuth,(req,res)=>res.json(dashboardData()));
app.get('/api/admin/orders',adminAuth,(req,res)=>res.json(read(FILES.orders).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))));app.get('/api/admin/inventory',adminAuth,(req,res)=>res.json(read(FILES.products)));app.get('/api/admin/customizations',adminAuth,(req,res)=>res.json(read(FILES.custom)));
app.post('/api/admin/products',adminAuth,(req,res)=>{const b=req.body||{};if(!b.name||!b.price||!b.category)return res.status(400).json({error:'Name, category and price are required.'});const p={id:String(b.name).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now().toString().slice(-5),name:String(b.name),category:String(b.category),material:String(b.material||'Custom finish'),price:Number(b.price),image:String(b.image||''),customizable:Boolean(b.customizable),colors:Array.isArray(b.colors)?b.colors:[],fabrics:Array.isArray(b.fabrics)?b.fabrics:[],dimensions:{width:Number(b.dimensions?.width||0),depth:Number(b.dimensions?.depth||0),height:Number(b.dimensions?.height||0)},stock:Number(b.stock||0)};const rows=read(FILES.products);rows.push(p);write(FILES.products,rows);res.json(p)});
app.put('/api/admin/products/:id',adminAuth,(req,res)=>{const rows=read(FILES.products),i=rows.findIndex(p=>p.id===req.params.id);if(i<0)return res.status(404).json({error:'Product not found'});rows[i]={...rows[i],...req.body,updatedAt:now()};write(FILES.products,rows);res.json(rows[i])});
app.post('/api/admin/orders/:id/status',adminAuth,(req,res)=>{const allowed=['payment_pending','confirmed','processing','packed','shipped','out_for_delivery','delivered','cancelled'];if(!allowed.includes(req.body?.status))return res.status(400).json({error:'Invalid order status'});const o=patchOrder(req.params.id,{status:req.body.status});if(!o)return res.status(404).json({error:'Order not found'});res.json(o)});
app.post('/api/admin/customizations/:id/status',adminAuth,(req,res)=>{const allowed=['submitted','reviewing','quoted','approved','closed'];if(!allowed.includes(req.body?.status))return res.status(400).json({error:'Invalid status'});const rows=read(FILES.custom),i=rows.findIndex(r=>r.id===req.params.id);if(i<0)return res.status(404).json({error:'Request not found'});rows[i]={...rows[i],status:req.body.status,updatedAt:now()};write(FILES.custom,rows);res.json(rows[i])});
app.get('*',(req,res)=>res.sendFile(path.join(ROOT,'public','index.html')));
app.listen(PORT,()=>console.log(`Leonora Furniture Studio running on :${PORT}; Razorpay ${razorReady?'ready':'not configured'}`));
