require('dotenv').config();
const express = require('express');
const cors = require('cors');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const nodemailer = require('nodemailer');
const Razorpay = require('razorpay');

const app = express();
const PORT = Number(process.env.PORT || 3000);
const ROOT = path.join(__dirname, '..');
const DATA = path.join(ROOT, 'data');
const FILES = { products: path.join(DATA,'products.json'), orders: path.join(DATA,'orders.json'), custom: path.join(DATA,'customization-requests.json'), events: path.join(DATA,'webhook-events.json') };
for (const file of Object.values(FILES)) if (!fs.existsSync(file)) fs.writeFileSync(file,'[]');
const read = file => JSON.parse(fs.readFileSync(file,'utf8'));
const write = (file, value) => fs.writeFileSync(file, JSON.stringify(value,null,2));
const now = () => new Date().toISOString();
const money = n => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n)||0);
const safe = v => String(v ?? '').replace(/[<>]/g,'');
const adminSessions = new Map();
const razorReady = Boolean(process.env.RAZORPAY_KEY_ID && process.env.RAZORPAY_KEY_SECRET);
const razorpay = razorReady ? new Razorpay({ key_id: process.env.RAZORPAY_KEY_ID, key_secret: process.env.RAZORPAY_KEY_SECRET }) : null;
const mailReady = Boolean(process.env.SMTP_HOST && process.env.SMTP_USER && process.env.SMTP_PASS);
const transporter = mailReady ? nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE).toLowerCase()==='true',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}}) : null;

app.use(cors());
app.use(express.json({limit:'1mb'}));
app.use(express.urlencoded({extended:true}));

function findProduct(id){ return read(FILES.products).find(p => p.id === id); }
function findOrder(id){ return read(FILES.orders).find(o => o.id === id || o.razorpayOrderId === id); }
function updateOrder(id, patch){ const rows=read(FILES.orders); const i=rows.findIndex(o=>o.id===id || o.razorpayOrderId===id); if(i<0)return null; rows[i]={...rows[i],...patch,updatedAt:now()}; write(FILES.orders,rows); return rows[i]; }
function adminAuth(req,res,next){ const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,''); if(!token||!adminSessions.has(token)) return res.status(401).json({error:'Admin session expired.'}); req.admin=adminSessions.get(token); next(); }
function verifySignature(orderId,paymentId,signature){ if(!process.env.RAZORPAY_KEY_SECRET)return false; const expected=crypto.createHmac('sha256',process.env.RAZORPAY_KEY_SECRET).update(`${orderId}|${paymentId}`).digest('hex'); return crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(String(signature||''))); }
function verifyWebhook(raw,signature){ if(!process.env.RAZORPAY_WEBHOOK_SECRET)return false; const expected=crypto.createHmac('sha256',process.env.RAZORPAY_WEBHOOK_SECRET).update(raw).digest('hex'); return crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(String(signature||''))); }
function makeOrderId(){ return `LEO-${Date.now().toString().slice(-8)}`; }
function makeCustomId(){ return `CUS-${Date.now().toString().slice(-8)}`; }
async function sendMail(to,subject,html){ if(!transporter || !to)return false; await transporter.sendMail({from:process.env.SMTP_FROM||process.env.SMTP_USER,to,subject,html}); return true; }
async function paidEmail(order){ if(order.confirmationEmailSentAt || !order.email)return; const items=order.items.map(i=>`<tr><td style="padding:10px 0">${safe(i.name)} × ${i.quantity}</td><td style="padding:10px 0;text-align:right">${money(i.price*i.quantity)}</td></tr>`).join(''); const html=`<!doctype html><html><body style="font-family:Arial,sans-serif;background:#f8f2ea;color:#191715;padding:40px"><div style="max-width:680px;margin:auto;background:white;padding:40px"><div style="font:30px Georgia,serif;letter-spacing:.08em">LEONORA</div><div style="letter-spacing:.22em;font-size:11px">FURNITURE STUDIO</div><hr style="border:0;border-top:1px solid #ded5ca;margin:28px 0"><h1 style="font:40px Georgia,serif;font-weight:400">Order confirmed ✓</h1><p>Thank you, ${safe(order.shipping?.name)}. Your payment was successfully verified.</p><p><strong>Order ${safe(order.id)}</strong></p><table style="width:100%;border-collapse:collapse">${items}</table><hr style="border:0;border-top:1px solid #ded5ca"><p style="display:flex;justify-content:space-between"><strong>Total paid</strong><strong>${money(order.total)}</strong></p><p style="color:#71695f">UPI and card payments are processed securely by Razorpay.</p></div></body></html>`; await sendMail(order.email,'Leonora order confirmed · '+order.id,html); order.confirmationEmailSentAt=now(); updateOrder(order.id,{confirmationEmailSentAt:order.confirmationEmailSentAt}); }
async function customEmail(request){ if(!transporter || !request.email)return; const html=`<div style="font-family:Arial,sans-serif;background:#f8f2ea;padding:40px;color:#191715"><div style="max-width:640px;margin:auto;background:white;padding:40px"><div style="font:30px Georgia,serif">LEONORA</div><div style="letter-spacing:.2em;font-size:11px">FURNITURE STUDIO</div><hr><h2 style="font:34px Georgia,serif;font-weight:400">Customisation request received</h2><p>Your request <strong>${safe(request.id)}</strong> for ${safe(request.productName)} has been submitted successfully.</p><p><strong>Selected finish:</strong> ${safe(request.color)} · ${safe(request.fabric||'N/A')}</p><p><strong>Dimensions:</strong> W ${request.dimensions.width} · D ${request.dimensions.depth} · H ${request.dimensions.height} cm</p><p>We will contact you regarding the quotation.</p></div></div>`; await sendMail(request.email,'Leonora customisation request received · '+request.id,html); }

app.post('/api/webhooks/razorpay', express.raw({type:'application/json'}), async (req,res)=>{ try{ const sig=req.headers['x-razorpay-signature']; const raw=Buffer.isBuffer(req.body)?req.body:Buffer.from(''); if(!verifyWebhook(raw,sig))return res.status(400).json({error:'Invalid webhook signature'}); const payload=JSON.parse(raw.toString('utf8')); const eventId=req.headers['x-razorpay-event-id']||crypto.createHash('sha256').update(raw).digest('hex'); const events=read(FILES.events); if(events.includes(eventId))return res.json({ok:true}); events.push(eventId); write(FILES.events,events); const orderId=payload.payload?.order?.entity?.id || payload.payload?.payment?.entity?.order_id; const paymentId=payload.payload?.payment?.entity?.id; if(['order.paid','payment.captured'].includes(payload.event) && orderId){ const order=findOrder(orderId); if(order){ const updated=updateOrder(order.id,{paymentStatus:'paid',status:'confirmed',razorpayPaymentId:paymentId||order.razorpayPaymentId,paidAt:order.paidAt||now()}); if(updated){ await paidEmail(updated).catch(()=>{}); const products=read(FILES.products); const changed=new Set(); for(const item of updated.items){ const p=products.find(x=>x.id===item.productId); if(p && !changed.has(item.productId)){p.stock=Math.max(0,Number(p.stock||0)-Number(item.quantity||0)); changed.add(item.productId);}} write(FILES.products,products); } } } if(payload.event==='payment.failed' && orderId) updateOrder(orderId,{paymentStatus:'failed',status:'cancelled'}); res.json({ok:true}); }catch(e){console.error(e);res.status(500).json({error:'Webhook processing failed'});} });

app.get('/api/config',(req,res)=>res.json({razorpayKeyId:process.env.RAZORPAY_KEY_ID||null,currency:'INR',ready:razorReady}));
app.get('/api/products',(req,res)=>res.json(read(FILES.products)));
app.get('/api/orders/:id',(req,res)=>{const o=findOrder(req.params.id); if(!o)return res.status(404).json({error:'Order not found'}); res.json(o);});

app.post('/api/orders/create',async(req,res)=>{ try{ const {email,phone,shipping,items}=req.body||{}; if(!email||!phone||!shipping?.name||!shipping?.address||!shipping?.pincode||!shipping?.city||!shipping?.state||!Array.isArray(items)||!items.length)return res.status(400).json({error:'Complete all checkout details.'}); const catalogue=read(FILES.products); const normalized=[]; for(const item of items){ const p=catalogue.find(x=>x.id===item.productId||x.id===item.id); if(!p)return res.status(400).json({error:'A selected product is unavailable.'}); const qty=Math.max(1,Number(item.quantity||1)); if(Number(p.stock||0)<qty)return res.status(400).json({error:`Only ${p.stock} units of ${p.name} are available.`}); normalized.push({productId:p.id,name:p.name,price:Number(p.price),quantity:qty,image:p.image,color:item.color||item.selectedColor||p.colors?.[0]||'',fabric:item.fabric||item.selectedFabric||p.fabrics?.[0]||''}); } const subtotal=normalized.reduce((s,i)=>s+i.price*i.quantity,0); const delivery=subtotal>=100000?0:2500; const total=subtotal+delivery; const id=makeOrderId(); const order={id,email,phone,shipping,items:normalized,subtotal,delivery,total,currency:'INR',status:'payment_pending',paymentStatus:'pending',createdAt:now(),updatedAt:now()}; const orders=read(FILES.orders); orders.push(order); write(FILES.orders,orders); if(!razorReady)return res.json({orderRef:id,razorpay:{key:process.env.RAZORPAY_KEY_ID||'',amount:Math.round(total*100),currency:'INR',orderId:null},mode:'setup'}); const rz=await razorpay.orders.create({amount:Math.round(total*100),currency:'INR',receipt:id,payment_capture:1,notes:{orderRef:id}}); updateOrder(id,{razorpayOrderId:rz.id}); res.json({orderRef:id,razorpay:{key:process.env.RAZORPAY_KEY_ID,amount:rz.amount,currency:rz.currency,orderId:rz.id}}); }catch(e){console.error(e);res.status(500).json({error:e.error?.description||e.message||'Unable to create order'});} });

app.post('/api/orders/verify',async(req,res)=>{ try{ const {razorpay_order_id,razorpay_payment_id,razorpay_signature,orderRef,orderId}=req.body||{}; const ref=orderRef||orderId; const order=findOrder(ref); if(!order)return res.status(404).json({error:'Order not found'}); if(!verifySignature(razorpay_order_id||order.razorpayOrderId,razorpay_payment_id,razorpay_signature))return res.status(400).json({error:'Payment verification failed'}); const updated=updateOrder(order.id,{razorpayOrderId:razorpay_order_id||order.razorpayOrderId,razorpayPaymentId:razorpay_payment_id,paymentStatus:'paid',status:'confirmed',paidAt:now()}); const products=read(FILES.products); const deducted=(updated.inventoryDeducted===true); if(!deducted){for(const item of updated.items){const p=products.find(x=>x.id===item.productId);if(p)p.stock=Math.max(0,Number(p.stock||0)-Number(item.quantity||0));}write(FILES.products,products);updateOrder(updated.id,{inventoryDeducted:true});} const final=findOrder(updated.id); await paidEmail(final).catch(()=>{}); res.json({ok:true,orderRef:final.id}); }catch(e){console.error(e);res.status(500).json({error:e.message||'Verification failed'});} });

app.post('/api/customization-requests',async(req,res)=>{ try{ const {productId,productName,email,phone,color,fabric,dimensions,notes}=req.body||{}; const p=findProduct(productId); if(!p||!p.customizable)return res.status(400).json({error:'This piece does not support customisation.'}); if(!email||!phone||!dimensions?.width||!dimensions?.depth||!dimensions?.height)return res.status(400).json({error:'Please add your contact details and all three measurements.'}); const request={id:makeCustomId(),productId,productName:productName||p.name,email,phone,color:color||p.colors?.[0]||'',fabric:fabric||p.fabrics?.[0]||'',dimensions:{width:Number(dimensions.width),depth:Number(dimensions.depth),height:Number(dimensions.height)},notes:String(notes||''),status:'submitted',createdAt:now(),updatedAt:now()}; const rows=read(FILES.custom);rows.push(request);write(FILES.custom,rows); await customEmail(request).catch(()=>{}); if(process.env.STUDIO_EMAIL)await sendMail(process.env.STUDIO_EMAIL,'New Leonora customisation request · '+request.id,`<p>${safe(request.productName)}</p><p>${safe(request.email)} · ${safe(request.phone)}</p><p>${safe(request.color)} · ${safe(request.fabric)}</p><p>W ${request.dimensions.width} · D ${request.dimensions.depth} · H ${request.dimensions.height} cm</p><p>${safe(request.notes)}</p>`).catch(()=>{}); res.json({ok:true,requestId:request.id,id:request.id}); }catch(e){res.status(500).json({error:e.message||'Unable to submit request'});} });

app.post('/api/admin/login',(req,res)=>{const email=String(req.body?.email||'');const password=String(req.body?.password||'');if(email!==String(process.env.ADMIN_EMAIL||'admin@leonora.in')||password!==String(process.env.ADMIN_PASSWORD||'LeonoraAdmin#2026'))return res.status(401).json({error:'Invalid admin credentials.'});const token=crypto.randomBytes(24).toString('hex');adminSessions.set(token,{email,createdAt:now()});res.json({token});});
app.post('/api/admin/logout',adminAuth,(req,res)=>{const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');adminSessions.delete(token);res.json({ok:true});});
app.get('/api/admin/dashboard',adminAuth,(req,res)=>{const orders=read(FILES.orders);const products=read(FILES.products);const custom=read(FILES.custom);const paid=orders.filter(o=>o.paymentStatus==='paid');const sales=paid.reduce((s,o)=>s+Number(o.total||0),0);const fulfilment={Delivered:paid.filter(o=>o.status==='delivered').length,Shipped:paid.filter(o=>['shipped','out_for_delivery'].includes(o.status)).length,Processing:paid.filter(o=>['confirmed','processing','packed'].includes(o.status)).length};const recent=orders.slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,6);const orderBars=Array.from({length:12},(_,i)=>Math.min(100,20+((orders.length*7+i*13)%74)));const salesBars=orderBars.map(v=>Math.round(v*.9));const monthly=Array.from({length:12},(_,i)=>18+((sales/100000+i*11)%66));res.json({totalOrders:orders.length,paidOrders:paid.length,totalSales:sales,customRequests:custom.filter(r=>r.status!=='closed').length,inventoryUnits:products.reduce((s,p)=>s+Number(p.stock||0),0),lowStock:products.filter(p=>Number(p.stock||0)<5).length,recent,orderBars,salesBars,monthly,fulfilment:{Delivered:paid.length?Math.round(fulfilment.Delivered/paid.length*100):0,Shipped:paid.length?Math.round(fulfilment.Shipped/paid.length*100):0,Processing:paid.length?Math.round(fulfilment.Processing/paid.length*100):0}});});
app.get('/api/admin/orders',adminAuth,(req,res)=>res.json(read(FILES.orders).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))));
app.get('/api/admin/inventory',adminAuth,(req,res)=>res.json(read(FILES.products)));
app.get('/api/admin/customizations',adminAuth,(req,res)=>res.json(read(FILES.custom).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))));
app.post('/api/admin/products',adminAuth,(req,res)=>{const b=req.body||{};if(!b.name||!b.price||!b.category)return res.status(400).json({error:'Name, category and price are required.'});const p={id:(String(b.name).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'piece')+'-'+Date.now().toString().slice(-5),name:String(b.name),category:String(b.category),material:String(b.material||'Custom finish'),price:Number(b.price),image:String(b.image||''),customizable:Boolean(b.customizable),colors:Array.isArray(b.colors)?b.colors:[],fabrics:Array.isArray(b.fabrics)?b.fabrics:[],dimensions:{width:Number(b.dimensions?.width||0),depth:Number(b.dimensions?.depth||0),height:Number(b.dimensions?.height||0)},stock:Number(b.stock||0)};const rows=read(FILES.products);rows.push(p);write(FILES.products,rows);res.json(p);});
app.put('/api/admin/products/:id',adminAuth,(req,res)=>{const rows=read(FILES.products);const i=rows.findIndex(p=>p.id===req.params.id);if(i<0)return res.status(404).json({error:'Product not found'});rows[i]={...rows[i],...req.body,updatedAt:now()};write(FILES.products,rows);res.json(rows[i]);});
app.post('/api/admin/orders/:id/status',adminAuth,(req,res)=>{const allowed=['payment_pending','confirmed','processing','packed','shipped','out_for_delivery','delivered','cancelled'];if(!allowed.includes(req.body?.status))return res.status(400).json({error:'Invalid order status'});const o=updateOrder(req.params.id,{status:req.body.status});if(!o)return res.status(404).json({error:'Order not found'});res.json(o);});
app.post('/api/admin/customizations/:id/status',adminAuth,(req,res)=>{const allowed=['submitted','reviewing','quoted','approved','closed'];if(!allowed.includes(req.body?.status))return res.status(400).json({error:'Invalid status'});const rows=read(FILES.custom);const i=rows.findIndex(r=>r.id===req.params.id);if(i<0)return res.status(404).json({error:'Request not found'});rows[i]={...rows[i],status:req.body.status,updatedAt:now()};write(FILES.custom,rows);res.json(rows[i]);});
app.get('*',(req,res)=>res.sendFile(path.join(ROOT,'public','index.html')));
app.listen(PORT,()=>console.log(`Leonora running on :${PORT}; Razorpay ${razorReady?'ready':'not configured'}`));
